name: Arc Checker (Live Preview)

on:
  workflow_dispatch:

jobs:
  arc_checker_preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install feedparser requests
          pip install --upgrade git+https://github.com/Cannibal-Turtle/rss-feed.git@main

      - name: Run arc checker dry-run (but post to Discord)
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}

          # ↓↓↓ VERY IMPORTANT ↓↓↓
          # false = send messages to Discord,
          # true  = print only (no send)
          DRY_RUN: "false"
        run: python new_arc_checker_dryrun.py
