name: Test Bot Completion Post

on:
  workflow_dispatch:

jobs:
  send_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Run test_bot_post
        env:
          # map your repository secrets into exactly the names your script expects:
          DISCORD_BOT_TOKEN:   ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CHANNEL_ID:  ${{ secrets.DISCORD_CHANNEL_ID }}
        run: python test_bot_post.py
