name: Test New Novel Launch Message

on:
  workflow_dispatch:

jobs:
  test_new_launch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install feedparser requests python-dateutil
          pip install --upgrade git+https://github.com/Cannibal-Turtle/rss-feed.git@main

      - name: Run test launch script
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
        run: python new_novel_checker_test.py
